repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Git style
      - id: check-added-large-files # prevents giant files from being committed.
      - id: no-commit-to-branch # don't commit to branch

      # Common errors
      - id: trailing-whitespace # trims trailing whitespace.
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline.
      - id: check-merge-conflict # checks for files that contain merge conflict strings.
      - id: check-executables-have-shebangs # ensures that (non-binary) executables have a shebang.


  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.80.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args: ["--args=--lockfile=false"]
